### ISSUE TITLE
Run in CI

### ISSUE THREAD

**Issue by keilw** [cruftex/jsr107-test-zoo#11]
Hi,

Looks great, one would have expected something similar from the actual JSR (maybe for a future version, I recommended to offer you listing as Contributor under JCP 2.10) 

How complicated is it to make the "live" results visible in a CI server like Travis, etc.?
(at least for all implementations that are not proprietary)

**Comment by cruftex** [comment]
> Looks great, one would have expected something similar from the actual JSR

Yes, its planned to move it over, so that somebody else can merge something in, too. I went on other tasks first.

> How complicated is it to make the "live" results visible in a CI server like Travis, etc.?

The test zoo tests stable versions of implementations against a stable version of a TCK.

Since incubation the TCK hasn't changed. Implementations and its major versions change rarely, too.

What exactly should be continuously integrated?

Hopefully every vendor has a CI and check their ongoing development for compliance...

Actually, I regenerate the result summary every time, which is here:
https://github.com/cruftex/jsr107-test-zoo/blob/master/report.md

A CI server would just produce the same.

**Comment by keilw** [comment]
Well if the readme is generated automatically (or at least semi-automatically) that comes close. 
I believe there's also a more or less static page on jcp.org or somewhere else with a kind of compatibility list. Backing that is a good idea.
